id = "ard"
name = "Ard"
version = "0.0.1"
schema_version = 1
authors = ["Akonwi Ngoh <akonwi@gmail.com>"]
description = "Language support for Ard"
repository = "https://github.com/akonwi/ard"

[grammars.ard]
repository = "file:///Users/akonwi/Developer/agent/ard/tree-sitter-ard"
commit = "0cf7f4e8a313d3648ac7b813bbceb32191749494"
